######################################################################
# Automatically generated by qmake (3.0) Thu Jun 6 23:22:20 2013
######################################################################

TEMPLATE = app
TARGET = gui
INCLUDEPATH += .

# Input
HEADERS += gui.hpp
SOURCES += bgsub.cpp guip.cpp
QT      += widgets
QT      += gui core
